//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdditionalInfoParser {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdditionalInfoParser.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на apartment.
        /// </summary>
        internal static string apartment {
            get {
                return ResourceManager.GetString("apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на assisted living.
        /// </summary>
        internal static string assistedliving {
            get {
                return ResourceManager.GetString("assistedliving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на attached garage.
        /// </summary>
        internal static string attachedgarage {
            get {
                return ResourceManager.GetString("attachedgarage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на carport.
        /// </summary>
        internal static string carport {
            get {
                return ResourceManager.GetString("carport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на cats are OK - purrr.
        /// </summary>
        internal static string catsok {
            get {
                return ResourceManager.GetString("catsok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на condo.
        /// </summary>
        internal static string condo {
            get {
                return ResourceManager.GetString("condo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на cottage/cabin.
        /// </summary>
        internal static string cottagecabin {
            get {
                return ResourceManager.GetString("cottagecabin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data Source=rentml.database.windows.net;Initial Catalog=CraigsList;Persist Security Info=True;User ID=rentml;Password=mlrent-1404;TrustServerCertificate=True.
        /// </summary>
        internal static string DbConnectionString {
            get {
                return ResourceManager.GetString("DbConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на detached garage.
        /// </summary>
        internal static string detachedgarage {
            get {
                return ResourceManager.GetString("detachedgarage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на dogs are OK - wooof.
        /// </summary>
        internal static string dogsok {
            get {
                return ResourceManager.GetString("dogsok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на duplex.
        /// </summary>
        internal static string duplex {
            get {
                return ResourceManager.GetString("duplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на flat.
        /// </summary>
        internal static string flat {
            get {
                return ResourceManager.GetString("flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на furnished.
        /// </summary>
        internal static string furnished {
            get {
                return ResourceManager.GetString("furnished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на house.
        /// </summary>
        internal static string house {
            get {
                return ResourceManager.GetString("house", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на in-law.
        /// </summary>
        internal static string inlaw {
            get {
                return ResourceManager.GetString("inlaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AdditionalInfoInsert.
        /// </summary>
        internal static string InsertProcedure {
            get {
                return ResourceManager.GetString("InsertProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на land.
        /// </summary>
        internal static string land {
            get {
                return ResourceManager.GetString("land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на laundry in bldg.
        /// </summary>
        internal static string laundryinbldg {
            get {
                return ResourceManager.GetString("laundryinbldg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на laundry on site.
        /// </summary>
        internal static string laundryonsite {
            get {
                return ResourceManager.GetString("laundryonsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на loft.
        /// </summary>
        internal static string loft {
            get {
                return ResourceManager.GetString("loft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на manufactured.
        /// </summary>
        internal static string manufactured {
            get {
                return ResourceManager.GetString("manufactured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на no laundry on site.
        /// </summary>
        internal static string nolaundryonsite {
            get {
                return ResourceManager.GetString("nolaundryonsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на no parking.
        /// </summary>
        internal static string noparking {
            get {
                return ResourceManager.GetString("noparking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на no smoking.
        /// </summary>
        internal static string nosmoking {
            get {
                return ResourceManager.GetString("nosmoking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10.
        /// </summary>
        internal static string NumberOfThreads {
            get {
                return ResourceManager.GetString("NumberOfThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на off-street parking.
        /// </summary>
        internal static string offstreetparking {
            get {
                return ResourceManager.GetString("offstreetparking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на street parking.
        /// </summary>
        internal static string streetparking {
            get {
                return ResourceManager.GetString("streetparking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на townhouse.
        /// </summary>
        internal static string townhouse {
            get {
                return ResourceManager.GetString("townhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на valet parking.
        /// </summary>
        internal static string valetparking {
            get {
                return ResourceManager.GetString("valetparking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на w/d hookups.
        /// </summary>
        internal static string wdhookups {
            get {
                return ResourceManager.GetString("wdhookups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на w/d in unit.
        /// </summary>
        internal static string wdinunit {
            get {
                return ResourceManager.GetString("wdinunit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на wheelchair accessible.
        /// </summary>
        internal static string wheelchairaccess {
            get {
                return ResourceManager.GetString("wheelchairaccess", resourceCulture);
            }
        }
    }
}
